config/routes.rb
Rails.application.routes.draw do

  root :to => "pages#index"
  resources :creatures
  resources :creature_locations
  resources :games
  resources :locations
  resources :moves
  resources :trades
  resources :users
  resources :user_battles
  resources :user_creatures
  resources :user_creature_moves
  resources :user_menus
  resources :user_trades



end

app/models/creature.rb
class Creature < ActiveRecord::Base
	has_many :moves
end

app/models/creature_location.rb
class CreatureLocation < ActiveRecord::Base
	has_many :creatures
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/move.rb
class Move < ActiveRecord::Base
	belongs_to :creature
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	has_many :user_trades
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_creatures

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_battle.rb
class UserBattle < ActiveRecord::Base
	has_many :moves
	has_many :creatures
	has_many :user_creatures
	has_many :user_creature_moves
end

app/models/user_creature.rb
class UserCreature < ActiveRecord::Base
	belongs_to :user
	has_many :user_creature_moves
end

app/models/user_creature_move.rb
class UserCreatureMove < ActiveRecord::Base
	belongs_to :user_creature
end

app/models/user_menu.rb
class UserMenu < ActiveRecord::Base
end

app/models/user_trade.rb
class UserTrade < ActiveRecord::Base
	has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
    render :template => "creatures/index"
  end

  def show
      @creature = Creature.find(params[:id])
      render :template => "creatures/show"
  end

  def new
  	@creature = Creature.new
    render :template => "creatures/new"
  end

  def create
  	 @creature = Creature.new(creature_params)
  	 if @creature.save
     	redirect_to creatures_path(@creature.id)
     else
        render :template => "creatures/new"
     end
  end

  def edit
    @item = Creature.find(params[:id])
    render :template => "creatures/edit"
  end

  def update
      @creature = Creature.find(params[:id])
      if @creature.update(creature_params)
      redirect_to creature_path
      else
      render :template => "creatures/edit"
      end
  end

  def destroy
        Creature.find(params[:id]).destroy!
        redirect_to creatures_path
  end
  
  def creature_params
    params.require(:creature).permit!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
	end

	def show
	end

	def create
	end

	def update
	end

	def delete
	end

	def new
	end

	def edit
	end

	def save
	end

	def load
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def retrieve
	end

	def show
		@locaion = Location.find(params[:id])
		render :template => "locations/show"
	end

end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

	def index
		@moves = Move.all
    render :template => "moves/index"
	end

	def show
		@move = Move.find(params[:id])
      	render :template => "moves/show"
	end

	def new
  	@move = Move.new
    render :template => "moves/new"
  	end

  def create
  	 @move = Move.new(move_params)
  	 if @move.save
     	redirect_to moves_path(@move.id)
     else
        render :template => "moves/new"
     end
  end

  def edit
    @item = Move.find(params[:id])
    render :template => "moves/edit"
  end

  def update
      @move = Move.find(params[:id])
      if @move.update(move_params)
      redirect_to move_path
      else
      render :template => "moves/edit"
      end
  end

  def destroy
        Move.find(params[:id]).destroy!
        redirect_to moves_path
  end
  
  def move_params
    params.require(:move).permit!
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def index
     render(:template => "pages/index")
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

	def index
	end

	def show
	end

end

app/controllers/user_menus_controller.rb
class UserMenusController < ApplicationController

	def index
	end

	def walk
	end

	def trade
	end

	def save_game
	end

	def view_monster_party
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creature/index.html.erb
<h1>Creatures</h1>
<%= link_to "New Creature", new_creature_path %>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Type</th>
     <th>Description</th>
  </tr>
  <% @creatures.each do |creature| %>
    <tr>
      <td><%= creature.name %></td>
      <td><%= creature.type %></td>
      <td><%= creature.description %></td>
      <td><%= link_to "Show", creature_path(creature.id) %></td>
      <td><%= link_to "Update", edit_creature_path(creature.id) %></td>
      <td><%= link_to "Destroy", creature_path(creature.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>
<br>

app/views/creatures/_form.html.erb
<%= simple_nested_form_for(@creature) do |f| %>
  
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :ctype %>
    <%= f.input :description %>
    <%= f.input :hp %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>	
  </div>

<% end %>

<%= link_to "Back to Creatures", creatures_path %>

app/views/creatures/edit.html.erb
Edit

app/views/creatures/index.html.erb
<h1>Creatures</h1>
<%= link_to "New Creature", new_creature_path %>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Type</th>
     <th>Description</th>
     <th> HP </th>
  </tr>
  <% @creatures.each do |creature| %>
    <tr>
      <td><%= creature.name %></td>
      <td><%= creature.ctype %></td>
      <td><%= creature.description %></td>
      <td><%= creature.hp %></td>
      <td><%= link_to "Show", creature_path(creature.id) %></td>
      <td><%= link_to "Update", edit_creature_path(creature.id) %></td>
      <td><%= link_to "Destroy", creature_path(creature.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>
<br>

app/views/creatures/new.html.erb
<!--%= link_to "Logout", destroy_user_session_path, :method => :delete %-->
<%= render 'form' %>

<%= link_to "Back to Creatures", creatures_path %>

app/views/creatures/show.html.erb
<h1><%= @creature.name %> </h1>

<strong>HP</strong>: <%= @creature.hp %> <br>
<strong>Type</strong>: <%= @creature.ctype %> <br>
<strong>Description</strong>: <%= @creature.description %> <br>
<br>
<br>
<%= link_to "Back to Creatures", creatures_path %>

app/views/moves/_form.html.erb
<%= simple_nested_form_for(@move) do |f| %>
  
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :max_number %>
    <%= f.input :mtype %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>	
  </div>

<% end %>

<%= link_to "Back to Moves", moves_path %>

app/views/moves/index.html.erb
<h1>Moves</h1>
<%= link_to "New Move", new_move_path %>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Maximum Number</th>
     <th>Move Type</th>
  </tr>
  <% @moves.each do |move| %>
    <tr>
      <td><%= move.name %></td>
      <td><%= move.max_number %></td>
      <td><%= move.mtype %></td>
      <td><%= link_to "Show", move_path(move.id) %></td>
      <td><%= link_to "Update", edit_move_path(move.id) %></td>
      <td><%= link_to "Destroy", move_path(move.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>
<br>

app/views/moves/new.html.erb
<%= render 'form' %>